### ISSUE TITLE
dokumentointi vai dokumentaatio

### ISSUE THREAD

**Issue by epicharri** [mluukkai/ohjelmistotekniikka-kevat-2020#7]
Ohjeessa sanotaan:
"Määrittelydokumentti tehdään samaan tapaan kuin referenssiprojektista eli markdown-muodossa, sijoitetaan repositorion hakemistoon dokumentointi ja siihen tulee olla linkki repositorion README.md:stä."
Kuitenkin referenssiprojektissa hakemiston nimenä on dokumentaatio.
Tuo olisi varmaan hyvä olla ohjeessa sama kuin esimerkkiprojektissa, ettei tule turhia sekaannuksia.

**Comment by tulma95** [comment]
Loistava ehdotus! Muutettu ohjetta luomaan hakemisto 'dokumentaatio' niin kuin referenssiprojektissa on.
